import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { validateArticleBlocks, validateImage, articleUrl, articlePlainText, makeArticleBlock } from '../lib/article-blocks.mjs';

test('unsafe URLs and missing image descriptions are rejected', () => {
  for (const url of ['javascript:alert(1)', '//evil.test/x', 'data:image/svg+xml,x', 'https://user:pass@evil.test/x', '/\\evil.test']) assert.equal(articleUrl(url), false);
  assert.ok(articleUrl('https://example.test/cover.png'));
  assert.ok(articleUrl('/api/media/image.png'));
  assert.throws(() => validateImage({ src: '/image.png', alt: '' }, true));
});
test('all structured block types validate without dropping code indentation', () => {
  const blocks = ['text','image','quote','list','table','diagram','code','html','callout'].map(makeArticleBlock);
  blocks[0].text = 'Un texte.';
  Object.assign(blocks[1], { src: '/image.png', alt: 'Une illustration' });
  blocks[2].text = 'Une citation'; blocks[3].items = ['Une idée'];
  blocks[4].rows = [['A', 'B']];
  blocks[6].code = '  const value: number = 1;\n';
  blocks[8].text = 'Un point important.';
  const saved = validateArticleBlocks(blocks, true, 1);
  assert.equal(saved.length, 9);
  assert.equal(saved[6].code, blocks[6].code);
  assert.ok(articlePlainText({ sections: [{ heading: 'Titre', paragraphs: ['Ancien texte'], blocks: saved }] }).includes('Une citation'));
});
test('invalid graph/table/type and blank published blocks are refused', () => {
  assert.throws(() => validateArticleBlocks([{ type: 'toString' }]));
  assert.throws(() => validateArticleBlocks([{ type: 'script' }]));
  assert.throws(() => validateArticleBlocks([{ type: 'text', text: '' }], true));
  assert.throws(() => validateArticleBlocks([{ type: 'diagram', nodes: ['A'], edges: [{ from: 0, to: 2 }] }]));
  assert.throws(() => validateArticleBlocks([{ type: 'table', headers: ['A'], rows: [['A', 'B']] }]));
});
test('legacy articles, rich histories, private deletion, restore and conflicts', async () => {
  process.env.CMS_STORAGE = 'local';
  process.env.CMS_DATA_DIR = await mkdtemp(path.join(os.tmpdir(), 'journal-unit-'));
  const cms = await import('../lib/cms-store.mjs?journal-test');
  const token = await cms.createAccount({ email: 'journal@example.test', password: 'test-only-password-8372', key: await cms.setupKey() });
  const input = { title: 'Un journal complet', slug: 'un-journal-complet', summary: 'Résumé', category: 'Réflexion', date: '2026-10-03', status: 'draft', sections: [{ heading: 'Introduction', paragraphs: ['Ancien contenu'] }] };
  const draft = await cms.saveArticle(token, input);
  assert.equal((await cms.publicContent()).articles.length, 0);
  const rich = await cms.saveArticle(token, { ...draft, status: 'published', cover: { src: '/image.png', alt: 'Couverture', caption: 'Crédit' }, tags: ['IA', 'IA'], sections: [{ ...draft.sections[0], paragraphs: [], blocks: [{ ...makeArticleBlock('code'), code: '  const x: number = 1;', language: 'typescript' }] }] });
  assert.equal(rich.tags.length, 1);
  assert.equal(rich.history[0].sections[0].paragraphs[0], 'Ancien contenu');
  assert.equal((await cms.publicContent()).articles.length, 1);
  const revised = await cms.saveArticle(token, { ...rich, summary: 'Résumé révisé' });
  assert.deepEqual(revised.history[0].cover, rich.cover);
  assert.equal(revised.history[0].sections[0].blocks[0].language, 'typescript');
  await assert.rejects(cms.deleteArticle('invalid', revised), error => error.status === 401);
  await assert.rejects(cms.deleteArticle(token, rich), error => error.status === 409);
  await cms.deleteArticle(token, revised);
  assert.equal((await cms.publicContent()).articles.length, 0);
  assert.equal('deletedArticles' in await cms.publicContent(), false);
  assert.equal((await cms.adminContent(token)).deletedArticles.length, 1);
  const restored = await cms.restoreArticle(token, { id: revised.id });
  assert.equal(restored.status, 'draft');
  assert.equal((await cms.publicContent()).articles.length, 0);
  assert.equal((await cms.adminContent(token)).deletedArticles.length, 0);
  assert.equal(restored.cover.alt, 'Couverture');
  await cms.deleteArticle(token, restored);
  await cms.saveArticle(token, input);
  await assert.rejects(cms.restoreArticle(token, { id: restored.id }), error => error.status === 409);
  const stored = JSON.parse(await readFile(path.join(process.env.CMS_DATA_DIR, 'content.json'), 'utf8'));
  assert.equal(stored.deletedArticles.length, 1);
  const expected = stored.deletedArticles.map(({ article }) => ({ id: article.id, updatedAt: article.updatedAt }));
  await assert.rejects(cms.emptyTrash('invalid', { expected }), error => error.status === 401);
  await assert.rejects(cms.emptyTrash(token, {}), error => error.status === 400);
  await assert.rejects(cms.emptyTrash(token, { expected: [] }), error => error.status === 409);
  await assert.rejects(cms.emptyTrash(token, { expected: [...expected, ...expected] }), error => error.status === 400);
  await assert.rejects(cms.emptyTrash(token, { expected: expected.map(item => ({ ...item, updatedAt: 'outdated' })) }), error => error.status === 409);
  assert.equal((await cms.adminContent(token)).deletedArticles.length, 1);
  const activeBefore = (await cms.adminContent(token)).articles;
  assert.deepEqual(await cms.emptyTrash(token, { expected }), { ok: true, removed: 1 });
  assert.deepEqual((await cms.adminContent(token)).articles, activeBefore);
  assert.equal((await cms.adminContent(token)).deletedArticles.length, 0);
  await assert.rejects(cms.restoreArticle(token, { id: restored.id }), error => error.status === 404);
  assert.deepEqual(await cms.emptyTrash(token, { expected: [] }), { ok: true, removed: 0 });
});
