/* eslint-disable @next/next/no-img-element */
"use client";
import { useRef, useState } from 'react';
import { blockLabels, codeLanguages, makeArticleBlock } from '@/lib/article-blocks.mjs';

function WritingField({ label, value, onChange, rows = 7 }) {
  const ref = useRef();
  const format = (start, end) => {
    const field = ref.current; const from = field.selectionStart, to = field.selectionEnd;
    const selected = value.slice(from, to) || 'texte';
    onChange(value.slice(0, from) + start + selected + end + value.slice(to));
    requestAnimationFrame(() => { field.focus(); field.setSelectionRange(from + start.length, from + start.length + selected.length); });
  };
  return <div><label>{label}<textarea ref={ref} aria-label={label} rows={rows} value={value} onChange={event => onChange(event.target.value)} /></label><div className="journal-format-toolbar" role="group" aria-label={'Mise en forme : ' + label}><button type="button" onClick={() => format('**', '**')}>Gras</button><button type="button" onClick={() => format('*', '*')}>Italique</button><button type="button" onClick={() => format('`', '`')}>Code en ligne</button><button type="button" onClick={() => format('[', '](https://exemple.fr)')}>Lien</button></div></div>;
}
export function JournalImageFields({ image, onChange, title, onBusy, onError }) {
  const current = image || { src: '', alt: '', caption: '' };
  const update = (key, value) => onChange({ ...current, [key]: value });
  const upload = async event => {
    const file = event.target.files?.[0]; if (!file) return;
    onBusy(true); onError('');
    try {
      if (file.size > 4 * 1024 * 1024) throw new Error('Utilisez une image de 4 Mo maximum, compatible avec le déploiement Vercel.');
      const data = new FormData(); data.append('file', file);
      const response = await fetch('/api/admin/media', { method: 'POST', body: data });
      const result = await response.json(); if (!response.ok) throw new Error(result.error);
      onChange({ ...current, src: result.src });
    } catch (error) { onError(error.message); }
    finally { onBusy(false); event.target.value = ''; }
  };
  return <fieldset className="journal-image-fields"><legend>{title}</legend><label>Importer {title.toLowerCase()}<input aria-label={'Importer ' + title.toLowerCase()} type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={upload} /><small>PNG, JPEG, WebP ou GIF · 4 Mo maximum. Les schémas exportés comme images sont aussi acceptés.</small></label><label>Adresse {title.toLowerCase()}<input aria-label={'Adresse ' + title.toLowerCase()} type="url" value={current.src} onChange={event => update('src', event.target.value)} placeholder="https://… ou /api/media/…" /></label><label>Description {title.toLowerCase()}<input aria-label={'Description ' + title.toLowerCase()} value={current.alt} maxLength={500} onChange={event => update('alt', event.target.value)} /><small>Décrivez ce que montre l’image. Cette description est nécessaire avant publication.</small></label><label>Légende {title.toLowerCase()}<input aria-label={'Légende ' + title.toLowerCase()} value={current.caption} maxLength={1000} onChange={event => update('caption', event.target.value)} /></label>{current.src && <><img src={current.src} alt={current.alt || 'Image en cours de rédaction'} referrerPolicy="no-referrer" /><button type="button" className="admin-text-button" onClick={() => onChange(null)}>Retirer cette image</button></>}</fieldset>;
}
export function BlockFields({ block, update, onBusy, onError }) {
  const field = (label, key, rows) => <label className={rows ? 'journal-source' : undefined}>{label}{rows ? <textarea aria-label={label} rows={rows} value={block[key] || ''} onChange={event => update({ [key]: event.target.value })} spellCheck={false} /> : <input aria-label={label} value={block[key] || ''} onChange={event => update({ [key]: event.target.value })} />}</label>;
  if (block.type === 'image') return <JournalImageFields image={block} title="Image du bloc" onChange={value => update(value || { src: '', alt: '', caption: '' })} onBusy={onBusy} onError={onError} />;
  if (['text', 'quote', 'callout'].includes(block.type)) return <>{block.type === 'callout' && <>{field('Titre de l’encadré', 'title')}<label>Style de l’encadré<select aria-label="Style de l’encadré" value={block.tone} onChange={event => update({ tone: event.target.value })}><option value="note">Note</option><option value="warning">Point de vigilance</option></select></label></>}<WritingField label={block.type === 'quote' ? 'Citation' : block.type === 'callout' ? 'Contenu de l’encadré' : 'Contenu du bloc texte'} value={block.text || ''} onChange={text => update({ text })} />{block.type === 'quote' && field('Auteur ou source', 'author')}</>;
  if (block.type === 'code') return <><label>Langage<select aria-label="Langage du code" value={block.language} onChange={event => update({ language: event.target.value })}>{codeLanguages.map(language => <option key={language}>{language}</option>)}</select></label>{field('Code à publier', 'code', 12)}{field('Légende du code', 'caption')}<p className="journal-setup-note">Le code sera affiché et copiable, sans être exécuté. L’indentation est conservée.</p></>;
  if (block.type === 'html') return <>{field('Source HTML de la démo', 'html', 10)}{field('Styles CSS de la démo', 'css', 8)}{field('Légende de la démo', 'caption')}<label>Hauteur de la démo (px)<input type="number" min={180} max={800} value={block.height} onChange={event => update({ height: Number(event.target.value) })} /></label><p className="journal-setup-note">L’aperçu affiche votre HTML et votre CSS dans un cadre isolé. Les scripts, les formulaires et les ressources externes sont bloqués. Pour partager du TypeScript, utilisez un bloc Code.</p></>;
  if (block.type === 'list') return <><label>Présentation de la liste<select aria-label="Présentation de la liste" value={block.ordered ? 'ordered' : 'plain'} onChange={event => update({ ordered: event.target.value === 'ordered' })}><option value="plain">À puces</option><option value="ordered">Numérotée</option></select></label><label>Éléments, un par ligne<textarea rows={6} value={block.items.join('\n')} onChange={event => update({ items: event.target.value.split('\n') })} /></label></>;
  if (block.type === 'table') return <>{field('Légende du tableau', 'caption')}<div className="journal-table-editor" tabIndex={0} role="region" aria-label="Édition du tableau"><table><thead><tr>{block.headers.map((value, index) => <th key={index}><input aria-label={'Titre colonne ' + (index + 1)} value={value} onChange={event => update({ headers: block.headers.map((cell, position) => position === index ? event.target.value : cell) })} /></th>)}<th>Actions</th></tr></thead><tbody>{block.rows.map((row, index) => <tr key={index}>{row.map((value, position) => <td key={position}><input aria-label={'Ligne ' + (index + 1) + ' colonne ' + (position + 1)} value={value} onChange={event => update({ rows: block.rows.map((cells, rowIndex) => rowIndex === index ? cells.map((cell, colIndex) => colIndex === position ? event.target.value : cell) : cells) })} /></td>)}<td><button type="button" className="admin-text-button" onClick={() => update({ rows: block.rows.filter((_, rowIndex) => rowIndex !== index) })}>Retirer ligne {index + 1}</button></td></tr>)}</tbody></table></div><div className="journal-block-toolbar"><button type="button" disabled={block.rows.length >= 50} onClick={() => update({ rows: [...block.rows, block.headers.map(() => '')] })}>Ajouter une ligne</button><button type="button" disabled={block.headers.length >= 10} onClick={() => update({ headers: [...block.headers, 'Nouvelle colonne'], rows: block.rows.map(row => [...row, '']) })}>Ajouter une colonne</button><button type="button" disabled={block.headers.length <= 1} onClick={() => update({ headers: block.headers.slice(0, -1), rows: block.rows.map(row => row.slice(0, -1)) })}>Retirer la dernière colonne</button></div></>;
  if (block.type === 'diagram') return <><label>Étapes du schéma, une par ligne<textarea rows={5} value={block.nodes.join('\n')} onChange={event => { const nodes = event.target.value.split('\n'); update({ nodes, edges: block.edges.filter(edge => edge.from < nodes.length && edge.to < nodes.length) }); }} /><small>Jusqu’à 12 étapes. Utilisez les relations ci-dessous pour montrer les dépendances ou les branches.</small></label>{block.edges.map((edge, index) => <div className="admin-field-row" key={index}><label>Départ relation {index + 1}<select aria-label={'Départ relation ' + (index + 1)} value={edge.from} onChange={event => update({ edges: block.edges.map((item, position) => position === index ? { ...item, from: Number(event.target.value) } : item) })}>{block.nodes.map((label, position) => <option key={position} value={position}>{position + 1}. {label}</option>)}</select></label><label>Arrivée relation {index + 1}<select aria-label={'Arrivée relation ' + (index + 1)} value={edge.to} onChange={event => update({ edges: block.edges.map((item, position) => position === index ? { ...item, to: Number(event.target.value) } : item) })}>{block.nodes.map((label, position) => <option key={position} value={position}>{position + 1}. {label}</option>)}</select></label><button type="button" className="admin-text-button" onClick={() => update({ edges: block.edges.filter((_, position) => position !== index) })}>Retirer relation {index + 1}</button></div>)}<button type="button" className="admin-secondary" disabled={block.nodes.length < 2 || block.edges.length >= 30} onClick={() => update({ edges: [...block.edges, { from: 0, to: 1 }] })}>Ajouter une relation</button>{field('Légende du schéma', 'caption')}</>;
  return null;
}
function SectionFields({ section, index, count, onChange, onMove, onRemove, onBusy, onError }) {
  const [kind, setKind] = useState('image'); const blocks = section.blocks || [];
  const editBlock = (position, changes) => onChange('blocks', blocks.map((block, i) => i === position ? { ...block, ...changes } : block));
  const move = (from, to) => { const next = [...blocks]; [next[from], next[to]] = [next[to], next[from]]; onChange('blocks', next); };
  return <fieldset className="admin-section"><legend>Section {index + 1}</legend><label>Titre de section<input value={section.heading} maxLength={200} onChange={event => onChange('heading', event.target.value)} /></label><WritingField label={'Texte de la section ' + (index + 1)} value={section.paragraphs.join('\n\n')} onChange={value => onChange('paragraphs', value.split(/\n\s*\n/))} /><small>Séparez les paragraphes par une ligne vide. Gras, italique, liens et code en ligne sont disponibles.</small>{blocks.map((block, position) => <div className="journal-block-editor" key={block.id || position}><div className="journal-block-toolbar"><strong>{position + 1}. {blockLabels[block.type]}</strong><button type="button" disabled={position === 0} onClick={() => move(position, position - 1)}>Monter le bloc {position + 1}</button><button type="button" disabled={position === blocks.length - 1} onClick={() => move(position, position + 1)}>Descendre le bloc {position + 1}</button><button type="button" onClick={() => onChange('blocks', [...blocks.slice(0, position + 1), { ...structuredClone(block), id: crypto.randomUUID() }, ...blocks.slice(position + 1)])}>Dupliquer le bloc {position + 1}</button><button type="button" onClick={() => { if (confirm('Retirer ce bloc de l’article ?')) onChange('blocks', blocks.filter((_, i) => i !== position)); }}>Retirer le bloc {position + 1}</button></div><BlockFields block={block} update={changes => editBlock(position, changes)} onBusy={onBusy} onError={onError} /></div>)}<div className="journal-insert"><label>Bloc à ajouter dans la section {index + 1}<select aria-label={'Bloc à ajouter dans la section ' + (index + 1)} value={kind} onChange={event => setKind(event.target.value)}>{Object.entries(blockLabels).map(([type, name]) => <option key={type} value={type}>{name}</option>)}</select></label><button type="button" className="admin-secondary" disabled={blocks.length >= 80} onClick={() => onChange('blocks', [...blocks, makeArticleBlock(kind)])}>Ajouter le bloc à la section {index + 1}</button></div><div className="journal-block-toolbar"><button type="button" disabled={!index} onClick={() => onMove(index - 1)}>Monter la section {index + 1}</button><button type="button" disabled={index === count - 1} onClick={() => onMove(index + 1)}>Descendre la section {index + 1}</button>{count > 1 && <button type="button" onClick={() => { if (confirm('Retirer cette section et ses blocs ?')) onRemove(); }}>Retirer la section {index + 1}</button>}</div></fieldset>;
}
export default function JournalEditorFields({ article, onChange, onBusy, onError }) {
  const sections = article.sections;
  const edit = (index, key, value) => onChange('sections', sections.map((section, position) => position === index ? { ...section, [key]: value } : section));
  const move = (from, to) => { const next = [...sections]; [next[from], next[to]] = [next[to], next[from]]; onChange('sections', next); };
  return <><JournalImageFields title="Image de couverture" image={article.cover} onChange={cover => onChange('cover', cover)} onBusy={onBusy} onError={onError} /><label>Mots-clés<input value={(article.tags || []).join(',')} onChange={event => onChange('tags', event.target.value.split(','))} /><small>Séparez les mots-clés par des virgules, 12 maximum.</small></label><details><summary>Titre et description pour les moteurs de recherche</summary><label>Titre SEO<input maxLength={200} value={article.seoTitle || ''} onChange={event => onChange('seoTitle', event.target.value)} /></label><label>Description SEO<textarea rows={3} maxLength={500} value={article.seoDescription || ''} onChange={event => onChange('seoDescription', event.target.value)} /></label></details>{sections.map((section, index) => <SectionFields key={section.id || index} section={section} index={index} count={sections.length} onChange={(key, value) => edit(index, key, value)} onMove={to => move(index, to)} onRemove={() => onChange('sections', sections.filter((_, position) => position !== index))} onBusy={onBusy} onError={onError} />)}<button type="button" className="admin-secondary" disabled={sections.length >= 40} onClick={() => onChange('sections', [...sections, { id: crypto.randomUUID(), heading: '', paragraphs: [''], blocks: [] }])}>Ajouter une section</button></>;
}
