export const projects = [
  // PROJETS CLIENT (existants)
  { slug:"mc2i-stream-ia-data-science", title:"mc2i – Tech Lead du Stream IA & Data Science", year:"01/2025 – En cours",
    teaser:"Tech Lead du Stream IA & Data Science au sein du Lab mc2i. Pilotage du portefeuille de POC IA, supervision technique, développement du média IA'ctualités et formation.",
    role:"Tech Lead du Stream IA & Data Science", context:"Innovation interne et R&D, développement de l'offre IA générative, communication et formation.",
    actions:["Pilotage du portefeuille de POC IA et cadrage des expérimentations", "Supervision technique (Streamlit, Django, Azure AI)", "Coordination et animation de la communauté Data & IA", "Création et pilotage du média IA'ctualités", "Formations internes et interventions dans les grandes écoles"],
    impact:["Structuration du portefeuille de POC", "Mise en place des standards de sécurité et conformité", "Diffusion de la culture IA au sein du cabinet", "Développement de supports pédagogiques"],
    stack:["Python","SQL","Streamlit","Django","FastAPI","Azure AI","AWS Bedrock","Power Platform"],
    tags:["Tech Lead","POC","Industrialisation","Conformité","Formation","Média"], kpis:["POC:Portefeuille structuré","Formations:Actives","Média:IA'ctualités"] },
  { slug:"totalenergies-ai4rt-ideation-ia", title:"TotalEnergies – AI4R&T – Accélération de l'innovation par l'IA générative", year:"05/2024 – En cours",
    teaser:"Chef de projet & Expert IA Générative pour la R&D. Pilotage de 40+ cas d'usage sur 5 lignes de recherche. Conception from scratch de plateformes RAG multi-modèles pour l'idéation technique et la PI.",
    role:"Chef de projet & Expert en Intelligence Artificielle", context:"R&D énergie, Brevets et Propriété Intellectuelle. 40+ cas d'usage répartis sur 5 lignes de recherche.",
    actions:["Cadrage des besoins métiers et identification des cas d'usage", "Conception from scratch de plateformes internes RAG multi-modèles", "Développement d'applications web (Django/Streamlit) sur Azure/AWS", "Mise en œuvre d'architecture RAG complète (ingestion, vectorisation, recherche, génération)", "Intégration multi-modèles : GPT-4 Turbo, Mistral, Claude Sonnet, Gemini", "Formation et acculturation IA (prompt engineering, PI, valorisation innovation)", "Industrialisation et transfert (scoring, infrastructure scalable, documentation)"],
    impact:["40+ cas d'usage pilotés", "Plateformes RAG opérationnelles", "Renforcement de la performance et qualité des déclarations d'invention", "Composants réutilisables et infrastructure scalable"],
    stack:["Python","Django","Streamlit","FastAPI","GPT-4 Turbo","Gemini","Claude Sonnet 3.5","Mistral","Azure AI","AWS Bedrock","Copilot Studio","FAISS","ChromaDB","Azure DevOps","Git","Docker","Power Automate"],
    tags:["RAG","LLM","Sécurité","PI","R&D","Multi-modèles"], kpis:["Cas d'usage:40+","Lignes de recherche:5","Modèles:4","Adoption:Équipes R&D"] },
  { slug:"ratp-pilotage-idfm-bi", title:"RATP – Pilotage des indicateurs de performance et de qualité de service IDFM", year:"05/2022 – 04/2024",
    teaser:"Chef de projet AMOA/AMOE Data & BI. Pilotage de 300+ indicateurs contractuels avec IDFM. Tableaux de bord pour instances dirigeantes et facturation.",
    role:"Chef de projet AMOA / AMOE Data & BI", context:"Transport de voyageurs, Finance et contrôle de gestion, Performance et qualité de service.",
    actions:["Cadrage et recueil des besoins pour 300+ indicateurs contractuels IDFM", "Développement d'applications et tableaux de bord (Power BI, QlikView, Cognos)", "Intégration et modélisation de données multi-SI", "Automatisation via Power Automate et optimisation des flux (Oracle Essbase, SQL Server)", "Maintien en condition opérationnelle (MCO) des outils décisionnels", "Formation et support utilisateurs sur Power Platform"],
    impact:["300+ indicateurs fiables et consolidés", "Visibilité financière et QoS pour le top management", "Alimentation des prévisions de facturation", "Maîtrise des indicateurs de production et performance financière"],
    stack:["Power BI","QlikView","Cognos","SQL","DAX","M","Python","VBA","MaxL","Oracle Essbase","SQL Server","Power Automate","Power Apps","GEDEM","Mantis"],
    tags:["BI","MCO","Performance","Finance","Transport"], kpis:["Indicateurs:300+","Directions:Multiples","Outils:3"] },
  { slug:"cojop-portail-olympiade-culturelle", title:"COJOP – Portail digital de l'Olympiade Culturelle Paris 2024", year:"10/2021 – 03/2022",
    teaser:"Product Owner Digital pour le portail web grand public de l'Olympiade Culturelle Paris 2024. Valorisation des initiatives culturelles et sportives, expérience utilisateur accessible et engageante.",
    role:"Product Owner", context:"Culture, Sport, Communication digitale.",
    actions:["Cadrage des besoins métiers pour le portail web", "Priorisation et gestion du backlog produit dans Jira", "Coordination des développements avec prestataires et suivi des livraisons sprint", "Contribution à la définition des parcours utilisateurs et architecture de l'information", "Validation des maquettes et intégration des retours métiers", "Veille sur l'accessibilité et la performance", "Gestion des retours utilisateurs et documentation fonctionnelle"],
    impact:["Expérience utilisateur fluide et inclusive", "Portail opérationnel pour l'Olympiade Culturelle", "Visibilité renforcée des programmes culturels et sportifs"], 
    stack:["Salesforce CMS","Algolia","Jira","Confluence","Scrum"],
    tags:["PO","UX","Accessibilité","Agile"], kpis:["Livraisons:Sprints","Accessibilité:Conforme"] },
  { slug:"lvmh-bi-rh-juridique", title:"LVMH – Pilotage décisionnel RH & Juridique", year:"01/2020 – 10/2021",
    teaser:"Chef de projet SI/BI pour les domaines RH et Juridique. Maintenance et évolution d'applications métiers, développement de solutions décisionnelles Power BI.",
    role:"Chef de projet SI", context:"DSI Groupe LVMH, enjeux RH & Juridique, Finance, Luxe.",
    actions:["Cadrage et priorisation des besoins métiers RH et Juridique", "Supervision de la maintenance et évolutions des applications (gestion du temps, suivi de carrière, lutte contre fraude/contrefaçon)", "Développement de tableaux de bord Power BI et QlikView", "Mise en œuvre de flux ETL pour extraction, transformation et consolidation des données", "Modélisation des données et création de rapports automatisés", "Conduite des tests et accompagnement au déploiement", "Gestion de la maintenance corrective et évolutive"],
    impact:["Pilotage opérationnel amélioré", "Visibilité accrue sur les coûts de formation, effectifs et parcours de carrière", "Applications métiers maintenues et évolutives"],
    stack:["Power BI","QlikView","SQL","DAX","M","SQL Server","Power Automate","Power Apps"],
    tags:["RH","Juridique","BI","Luxe"], kpis:["Rapports:Récurrents","Applications:Maintenues"] },
  { slug:"safran-datamro-mro", title:"Safran – DataMRO – Optimisation du suivi des pièces moteurs et des performances ateliers", year:"01/2019 – 12/2019",
    teaser:"Master Data & AI Manager. Supervision du projet DataMRO pour la fiabilisation des données de maintenance et production. Optimisation de la planification des réparations.",
    role:"Master Data & AI Manager", context:"Aéronautique et Maintenance, Gestion de production, Supply Chain.",
    actions:["Supervision du projet DataMRO pour fiabilisation des données", "Cadrage et modélisation du cycle de vie des pièces moteurs", "Analyse des écarts de quantités livrées et identification des anomalies", "Développement de scripts et outils d'analyse (VBA, Python)", "Création de tableaux de bord Power BI pour suivi des performances", "Définition d'indicateurs clés (KPIs) avec ingénieurs production et qualité", "Coordination avec Supply Chain, Support Client et Contrôle de gestion"],
    impact:["Fiabilisation des données de maintenance et production", "Disponibilité des pièces optimisée", "Pilotage MRO amélioré", "Performance des ateliers de réparation optimisée"],
    stack:["Python","VBA","Power BI","SQL Server","Excel","Power Automate"],
    tags:["MRO","Qualité données","BI","Aéronautique"], kpis:["Ateliers:Optimisés","Données:Fiabilisées"] },
  { slug:"vif-software-erp", title:"VIF Software – Déploiement et optimisation de l'ERP", year:"06/2018 – 11/2018",
    teaser:"Chef de projet ERP pour l'industrie agroalimentaire. Pilotage du déploiement et optimisation de l'ERP, alignement besoins métiers (production, logistique, qualité) et fonctionnalités système.",
    role:"Chef de projet ERP", context:"Agroalimentaire, Gestion de production, Logistique et achats.",
    actions:["Cadrage des besoins fonctionnels et définition des spécifications métiers", "Planification des étapes de déploiement et coordination équipes client/techniques", "Validation des flux métiers (production, logistique, qualité)", "Paramétrage des modules ERP (réception, fabrication, conditionnement)", "Intégration des flux de données entre systèmes atelier et ERP", "Test et validation des scénarios d'utilisation", "Formation des utilisateurs métiers et rédaction de supports", "Support post-déploiement et suivi des indicateurs de performance"],
    impact:["ERP déployé et opérationnel", "Processus alignés entre production, logistique et qualité", "Utilisateurs formés et autonomes", "Performance opérationnelle suivie (production, coûts, délais)"],
    stack:["VIF ERP","VBA","Scripts Shell","SQL Server","Excel","Power BI"],
    tags:["ERP","Agroalimentaire","Production","Logistique"], kpis:["Déploiement:Réussi","Modules:Paramétrés"] },

  // PROJETS INTERNES MC2I - Plateformes & builders IA / Data
  { slug:"iactualites-media-gpt-builder", title:"IA'ctualités – Média + GPT Builder éditorial", year:"2025 – En cours",
    teaser:"Média interne de veille et acculturation IA + GPT Builder dédié (ton, sources, consignes éditoriales). Veille, tribunes, analyses de fond sur les enjeux technologiques et métiers de l'IA.",
    role:"Créateur & Animateur", context:"Communication interne, acculturation IA, veille stratégique.",
    actions:["Création et pilotage du média IA'ctualités", "Rédaction d'articles, tribunes et analyses de fond", "Conception du GPT Builder éditorial (persona, règles, sources)", "Organisation d'événements et retours d'expérience", "Diffusion de la culture IA au sein du cabinet"],
    impact:["Média opérationnel et régulièrement alimenté", "GPT Builder pour standardiser le ton et les sources", "Acculturation IA renforcée", "Communauté engagée"],
    stack:["OpenAI GPT Builder","Azure AI","Content Management","Markdown"],
    tags:["Média","GPT Builder","Veille","Acculturation"], kpis:["Articles:Publiés","GPT:Opérationnel"] },
  { slug:"rao-rfp-gpt-builder", title:"RAO / RFP GPT Builder", year:"2025 – En prod",
    teaser:"Analyse automatisée d'appels d'offres : synthèse, matrices d'exigences, identification des risques, Q&A. Workflow complet d'ingestion → scoring → livrables structurés.",
    role:"Concepteur & Développeur", context:"Support commercial, analyse de marchés, réponse aux appels d'offres.",
    actions:["Conception du prompt système d'analyse", "Développement du workflow (ingestion → scoring → livrables)", "Création des matrices d'exigences automatisées", "Intégration de la détection de risques", "Génération de Q&A contextuel"],
    impact:["Gain de temps sur l'analyse de RAO/RFP", "Synthèses structurées et exploitables", "Matrices d'exigences standardisées", "Identification proactive des risques"],
    stack:["OpenAI GPT-4","Python","Prompt Engineering","Structured Output"],
    tags:["GPT Builder","RAO","RFP","Automatisation"], kpis:["Temps:50% réduit","Synthèses:Générées"] },
  { slug:"rag-as-a-service", title:"RAG-as-a-Service / RAG on Demand", year:"2025 – Proto",
    teaser:"Micro-outils RAG plug-and-play pour corpus client/internal. Architecture complète : ingestion, vectorisation, recherche, génération. Déploiement rapide et scalable.",
    role:"Architecte & Développeur", context:"Réutilisation de composants RAG, industrialisation, POC rapides.",
    actions:["Conception de l'architecture RAG modulaire", "Développement des composants (ingest/vector/search/generate)", "Création d'interfaces minimalistes", "Benchmarking des performances", "Documentation et guides de déploiement"],
    impact:["POC RAG déployés en quelques heures", "Composants réutilisables", "Architecture scalable et maintenable", "Réduction des temps de développement"],
    stack:["Python","FastAPI","FAISS","ChromaDB","Azure AI","AWS Bedrock","Docker"],
    tags:["RAG","Service","Architecture","Réutilisation"], kpis:["Temps déploiement:80% réduit","Composants:Réutilisables"] },
  { slug:"cursor-llm-orchestrator", title:"Cursor-based LLM Orchestrator", year:"2025 – En cours",
    teaser:"Cadre pour industrialiser des prompts/projets IA : gestion de branches, tests automatisés, CI/CD. Conventions et bonnes pratiques pour le développement IA.",
    role:"Concepteur & Standardisateur", context:"Industrialisation du développement IA, qualité, maintenabilité.",
    actions:["Définition de l'arborescence de repository", "Création des conventions de nommage et structure", "Développement de tests automatisés de prompts", "Intégration CI/CD pour validation", "Documentation des bonnes pratiques"],
    impact:["Qualité des prompts améliorée", "Tests automatisés intégrés", "Workflow de développement standardisé", "Maintenabilité accrue"],
    stack:["Git","GitHub Actions","Python","Pytest","Prompt Testing"],
    tags:["Orchestration","CI/CD","Tests","Standards"], kpis:["Tests:Automatisés","Qualité:Améliorée"] },

  // PROJETS INTERNES MC2I - Apps & interfaces web
  { slug:"mc2i-innovation-hub", title:"mc2i Innovation Hub Interactive (React)", year:"2025 – En prod",
    teaser:"Hub de démos internes (Data/IA/Cyber) avec filtres par use case. Interface interactive pour découvrir et tester les innovations du Lab.",
    role:"Développeur Frontend", context:"Showcase interne, démonstration des capacités, acculturation.",
    actions:["Développement de l'interface React", "Création du système de filtres par use case", "Intégration des démos interactives", "Routage et navigation optimisée", "Design responsive et moderne"],
    impact:["Hub opérationnel et accessible", "Découverte facilitée des innovations", "Engagement des équipes", "Showcase efficace"],
    stack:["React","TypeScript","CSS Modules","React Router"],
    tags:["React","Hub","Démos","Showcase"], kpis:["Démos:Intégrées","Use cases:Filtrables"] },
  { slug:"chatbot-full-online", title:"Interface web 'Chatbot Full Online' (Next.js)", year:"2025 – En prod",
    teaser:"UI légère pour agents Azure OpenAI en production. Déploiement facile, authentification intégrée, logs d'usage. Interface minimaliste et performante.",
    role:"Développeur Fullstack", context:"Production, déploiement rapide, expérience utilisateur optimale.",
    actions:["Développement de l'interface Next.js", "Intégration Azure OpenAI", "Mise en place de l'authentification", "Système de logs d'usage", "Optimisation des performances"],
    impact:["Déploiement en production facilité", "Interface utilisateur fluide", "Monitoring intégré", "Expérience optimisée"],
    stack:["Next.js","TypeScript","Azure OpenAI","Auth","Logging"],
    tags:["Next.js","Chatbot","Production","UI"], kpis:["Déploiement:Rapide","UX:Optimisée"] },
  { slug:"fyne-by-mc2i", title:"FYNE-by-mc2i – Marque de démos/apps", year:"2025 – En prod",
    teaser:"Bannière commune pour démos publiques internes. Styleguide unifié, page d'accueil, tuiles de démo. Identité visuelle cohérente.",
    role:"Designer & Développeur", context:"Branding interne, cohérence visuelle, showcase unifié.",
    actions:["Création du styleguide", "Développement de la page d'accueil", "Conception des tuiles de démo", "Documentation de l'identité visuelle", "Intégration dans les projets"],
    impact:["Identité visuelle unifiée", "Cohérence des démos", "Branding renforcé", "Showcase professionnel"],
    stack:["HTML","CSS","Design System","Branding"],
    tags:["Branding","Styleguide","Démos","Design"], kpis:["Démos:Unifiées","Cohérence:100%"] },

  // PROJETS INTERNES MC2I - Cyber (jeux, formation, simulateurs)
  { slug:"cyber-15-niveaux", title:"Module cybersécurité '15 niveaux' (contenu généré IA)", year:"2025 – En prod",
    teaser:"Formation progressive en cybersécurité : 15 niveaux, scénarios dynamiques générés par IA, évaluation intégrée. Parcours adaptatif et engageant.",
    role:"Concepteur & Développeur", context:"Formation interne, gamification, acculturation cybersécurité.",
    actions:["Conception des 15 niveaux progressifs", "Développement de la génération de scénarios par IA", "Création du système d'évaluation intégré", "Design de l'interface utilisateur", "Intégration des feedbacks"],
    impact:["Formation progressive et adaptative", "Scénarios dynamiques et variés", "Engagement renforcé", "Évaluation continue"],
    stack:["Python","IA Générative","Gamification","Evaluation"],
    tags:["Cyber","Formation","Gamification","IA"], kpis:["Niveaux:15","Scénarios:Dynamiques"] },
  { slug:"crisis-sim-ransomware", title:"CRISIS_SIM – Simulateur de crise ransomware", year:"2025 – En prod",
    teaser:"Simulateur de gestion de crise ransomware : l'IA joue les PNJ, scoring des décisions, conséquences réalistes. Rôle RSSI par défaut.",
    role:"Concepteur & Développeur", context:"Formation RSSI, gestion de crise, sensibilisation.",
    actions:["Conception de l'arbre de décisions", "Développement des PNJ IA", "Création du système de scoring", "Design des écrans de jeu", "Intégration des règles de jeu"],
    impact:["Formation réaliste à la gestion de crise", "Décisions évaluées objectivement", "Sensibilisation renforcée", "Expérience immersive"],
    stack:["Python","IA Générative","Gamification","Scoring"],
    tags:["Cyber","Simulateur","Crise","RSSI"], kpis:["Scénarios:Multiples","Score:Objectif"] },
  { slug:"escape-game-cyber", title:"Escape game cyber (PNJ IA, puzzles, budgets, mots de passe)", year:"2025 – En prod",
    teaser:"Escape game pédagogique : salles à débloquer, pièges, mini-jeux, leçons embarquées. PNJ IA, gestion de budgets, puzzles de mots de passe.",
    role:"Concepteur & Développeur", context:"Formation ludique, engagement, apprentissage actif.",
    actions:["Conception de la carte des salles", "Développement des puzzles et mini-jeux", "Intégration des PNJ IA", "Création du système de budgets", "Design des boucles de feedback"],
    impact:["Apprentissage ludique et engageant", "Leçons embarquées naturelles", "Expérience immersive", "Rétention améliorée"],
    stack:["Python","IA Générative","Gamification","Puzzles"],
    tags:["Cyber","Escape Game","Gamification","Formation"], kpis:["Salles:Multiples","Engagement:Élevé"] },

  // PROJETS INTERNES MC2I - Outils Data/Cloud & archi
  { slug:"dc-validator", title:"DC-Validator (S3 + Lambda + API Gateway)", year:"2025 – En prod",
    teaser:"Upload web vers S3, analyse automatique via Lambda (checker.py), retours structurés JSON. Validation de données cloud-native.",
    role:"Architecte & Développeur", context:"Validation de données, architecture serverless, automatisation.",
    actions:["Conception de l'architecture serverless", "Développement de l'interface d'upload", "Création du checker.py (Lambda)", "Intégration API Gateway", "Format de réponse JSON structuré"],
    impact:["Validation automatisée", "Architecture scalable", "Temps de traitement réduit", "Intégration facile"],
    stack:["AWS S3","AWS Lambda","API Gateway","Python","JSON"],
    tags:["AWS","Serverless","Validation","Cloud"], kpis:["Temps:Automatisé","Scalabilité:Élevée"] },
  { slug:"pinecone-integration", title:"Intégration Pinecone (AWS Marketplace)", year:"2025 – En prod",
    teaser:"Vector DB managée pour RAG internes. Intégration AWS Marketplace, IAM, billing, indexation/recherche vectorielle.",
    role:"Architecte & Intégrateur", context:"Vector DB, RAG, infrastructure managée.",
    actions:["Intégration AWS Marketplace", "Configuration IAM et sécurité", "Mise en place du billing", "Développement des snippets d'indexation", "Création des fonctions de recherche"],
    impact:["Vector DB opérationnelle", "Infrastructure managée", "Intégration simplifiée", "Coûts maîtrisés"],
    stack:["Pinecone","AWS Marketplace","IAM","Python","Vector Search"],
    tags:["Vector DB","RAG","AWS","Infrastructure"], kpis:["Intégration:Complète","Performance:Optimale"] },
  { slug:"odin-nosing-energie", title:"Odin – Nosing énergie (veille & scoring marchés)", year:"2025 – En cours",
    teaser:"Ingestion multi-sources (RTE/CRE/DGEC/IEA/IRENA/ACER/ENTSO-E), scoring d'indicateurs, alertes. Veille stratégique sur les marchés énergétiques.",
    role:"Architecte Data & Développeur", context:"Veille stratégique, analyse de marchés, intelligence économique.",
    actions:["Conception de l'architecture d'ingestion", "Développement des connecteurs multi-sources", "Création du modèle de scoring v1", "Design du dashboard de veille", "Système d'alertes automatisées"],
    impact:["Veille automatisée multi-sources", "Scoring objectif des indicateurs", "Alertes proactives", "Décisions éclairées"],
    stack:["Python","ETL","Scoring","Dashboard","Alerting"],
    tags:["Veille","Énergie","Scoring","Data"], kpis:["Sources:7+","Alertes:Automatisées"] },
  { slug:"un-lien-flutter", title:"'UN LIEN' (Flutter) – Chat session sharer", year:"2025 – En prod",
    teaser:"Lien unique pour rejoindre la même session de chat. Application mobile iOS/Android, gestion de sessions partagées, fix de joint session.",
    role:"Développeur Mobile", context:"Partage de sessions, collaboration, expérience mobile.",
    actions:["Développement de l'app Flutter", "Conception du système de sessions partagées", "Résolution du problème de joint session", "Design des écrans iOS/Android", "Tests et validation"],
    impact:["Partage de sessions facilité", "Collaboration améliorée", "Expérience mobile optimale", "Problème technique résolu"],
    stack:["Flutter","Dart","Mobile","Session Management"],
    tags:["Flutter","Mobile","Session","Collaboration"], kpis:["Platformes:iOS/Android","Sessions:Partagées"] },

  // PROJETS INTERNES MC2I - Plates-formes d'apprentissage
  { slug:"i-am-data-ia", title:"I AM Data & IA – Portail formation", year:"2025 – En cours",
    teaser:"Portail de formation structuré : SE FORMER / S'ENTRAÎNER / S'ÉVALUER / AUTOMATISER. Roadmap de modules, placeholders 'Bientôt dispo', exercices pratiques.",
    role:"Concepteur & Product Owner", context:"Formation interne, montée en compétences, parcours d'apprentissage.",
    actions:["Conception de la structure du portail", "Définition de la roadmap des modules", "Création des placeholders", "Développement d'exemples d'exercices", "Design de l'interface utilisateur"],
    impact:["Portail structuré et clair", "Roadmap visible", "Parcours d'apprentissage défini", "Engagement des apprenants"],
    stack:["Web Platform","Content Management","Roadmap"],
    tags:["Formation","Portail","Parcours","Apprentissage"], kpis:["Modules:Planifiés","Structure:Claire"] },
  { slug:"kits-premier-algorithme", title:"Kits 'Créer votre premier algorithme'", year:"2025 – En prod",
    teaser:"Tutoriel complet : article + notebook Colab. Algorithme utile pour consultants (tri, scoring, décision). Démo sur dataset jouet.",
    role:"Auteur & Formateur", context:"Formation pratique, montée en compétences techniques, pédagogie.",
    actions:["Rédaction de l'article tutoriel", "Création du notebook Colab", "Développement de la démo sur dataset jouet", "Design des exercices pratiques", "Documentation complète"],
    impact:["Formation pratique accessible", "Notebooks réutilisables", "Apprentissage progressif", "Compétences développées"],
    stack:["Python","Jupyter","Colab","Pandas","Algorithms"],
    tags:["Formation","Tutoriel","Notebook","Pédagogie"], kpis:["Notebooks:Disponibles","Apprenants:Formés"] },

  // PROJETS INTERNES MC2I - Acculturation & produits support
  { slug:"templates-standards", title:"Templates & Standards (prompts, archi, doc)", year:"2025 – En prod",
    teaser:"Modèles prêts à l'emploi : templates de prompting, fiches d'architecture, checklists sécurité/PI. Standards réutilisables pour accélérer les projets.",
    role:"Standardisateur & Documentaliste", context:"Réutilisation, qualité, accélération des projets.",
    actions:["Création de templates de prompts", "Développement de fiches d'architecture RAG", "Conception de checklists sécurité/PI", "Documentation des standards", "Mise à disposition de la communauté"],
    impact:["Templates réutilisables", "Qualité standardisée", "Temps de développement réduit", "Bonnes pratiques partagées"],
    stack:["Templates","Documentation","Standards","Checklists"],
    tags:["Templates","Standards","Documentation","Réutilisation"], kpis:["Templates:Disponibles","Temps:30% réduit"] },
  { slug:"blind-prospection-challenge", title:"Blind Prospection Challenge (app)", year:"2025 – En prod",
    teaser:"Gamification de la prospection interne : règles, scoring, feedback. Application pour encourager et mesurer la prospection active.",
    role:"Concepteur & Développeur", context:"Gamification, prospection interne, engagement commercial.",
    actions:["Conception des règles v1", "Développement de l'application", "Création du système de scoring", "Design des écrans de résultats", "Anonymisation des données"],
    impact:["Prospection encouragée", "Engagement mesurable", "Résultats anonymisés", "Culture commerciale renforcée"],
    stack:["Web App","Gamification","Scoring","Analytics"],
    tags:["Gamification","Prospection","Challenge","Engagement"], kpis:["Participants:Actifs","Engagement:Mesuré"] },
  { slug:"mobilite-innovation-hub", title:"Mobilité interne & 'Innovation Hub' (concepts produits)", year:"2025 – Concept",
    teaser:"Plate-forme d'appels à POC, matching compétences ↔ besoins. User flow, écrans concept, KPI attendus. Facilitation de la mobilité interne.",
    role:"Product Designer & Concepteur", context:"Mobilité interne, innovation, matching compétences.",
    actions:["Conception du user flow", "Design des écrans concept", "Définition des KPI attendus", "Spécification fonctionnelle", "Prototypage"],
    impact:["Concept validé", "User flow optimisé", "KPI définis", "Vision produit claire"],
    stack:["Product Design","User Flow","Prototyping","KPI"],
    tags:["Concept","Mobilité","Innovation","Product"], kpis:["Concept:Validé","KPI:Définis"] },
];
export function getProjects(){ return projects; }
export function getProject(slug){ return projects.find(p => p.slug === slug); }
