import Link from "next/link";
import { notFound } from "next/navigation";
import { publishedArticles, readingMinutes } from "@/lib/journal";
import { pageMetadata, site } from "@/lib/site";
import ArticleContent, { ArticleImage } from '@/components/ArticleContent';
import ArticleAdminLink from '@/components/ArticleAdminLink';
export const dynamic = "force-dynamic";
export async function generateMetadata({ params }) { const { slug } = await params; const article=(await publishedArticles()).find(item => item.slug===slug); if (!article) return {}; const meta=pageMetadata(article.seoTitle || article.title,article.seoDescription || article.summary,"/journal/"+slug); return { ...meta, keywords: article.tags, openGraph: { ...meta.openGraph, type:"article", publishedTime:article.date, authors:[site.name], ...(article.cover?.src ? { images: [{url:article.cover.src,alt:article.cover.alt}] } : {}) } }; }
export default async function ArticlePage({ params }) {
  const { slug } = await params; const article=(await publishedArticles()).find(item => item.slug===slug); if (!article) notFound();
  const schema={ "@context":"https://schema.org", "@type":"Article", headline:article.title, description:article.summary, datePublished:article.date, dateModified:article.updatedAt, ...(article.cover?.src ? {image:new URL(article.cover.src,site.url).href} : {}), author:{ "@type":"Person",name:site.name,url:site.url+"/a-propos" },mainEntityOfPage:site.url+"/journal/"+slug };
  return <><header className={"u-page-intro u-wrap journal-cover-"+(article.layout?.cover || "classic")}><nav className="u-breadcrumb" aria-label="Fil d’Ariane"><Link href="/">Accueil</Link><span>/</span><Link href="/journal">Journal</Link></nav><ArticleAdminLink id={article.id} /><p className="u-label">{article.category}</p><h1>{article.title}</h1><p className="u-page-description">{article.summary}</p><div className="u-article-meta">{site.name} · <time dateTime={article.date}>{new Intl.DateTimeFormat("fr-FR",{ dateStyle:"long",timeZone:"UTC" }).format(new Date(article.date))}</time> · {readingMinutes(article)} min de lecture</div>{!!article.tags?.length && <div className="journal-tags">{article.tags.map(tag => <span key={tag}>{tag}</span>)}</div>}{article.layout?.cover !== "none" && <ArticleImage image={article.cover} cover />}</header><div className="u-wrap u-article-layout journal-article-frame">{!article.document?.enabled && article.layout?.toc !== false && <nav className="u-toc" aria-label="Sommaire"><p className="u-label">DANS CET ARTICLE</p>{article.sections.map(section => <a key={section.id} href={"#"+section.id}>{section.heading}</a>)}</nav>}<article className="u-prose"><ArticleContent article={article} /><div className="u-action-row"><Link href="/journal">Retour au journal</Link><Link href="/contact">Poursuivre la discussion</Link></div></article></div><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema).replace(/</g,"\\u003c") }} /></>;
}
